/*
 * This file is generated by jOOQ.
 */
package com.mackokodzi.analyticswarehouse;

import com.mackokodzi.analyticswarehouse.tables.CampaignStatistics;
import com.mackokodzi.analyticswarehouse.tables.records.CampaignStatisticsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CampaignStatisticsRecord> CAMPAIGN_STATISTICS_PKEY = Internal.createUniqueKey(CampaignStatistics.CAMPAIGN_STATISTICS, DSL.name("campaign_statistics_pkey"), new TableField[] { CampaignStatistics.CAMPAIGN_STATISTICS.ID }, true);
}
