/*
 * This file is generated by jOOQ.
 */
package com.mackokodzi.analyticswarehouse;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.campaign_statistics_id_seq</code>
     */
    public static final Sequence<Integer> CAMPAIGN_STATISTICS_ID_SEQ = Internal.createSequence("campaign_statistics_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
