/*
 * This file is generated by jOOQ.
 */
package com.mackokodzi.analyticswarehouse;


import com.mackokodzi.analyticswarehouse.tables.CampaignStatistics;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.campaign_statistics</code>.
     */
    public static final CampaignStatistics CAMPAIGN_STATISTICS = CampaignStatistics.CAMPAIGN_STATISTICS;
}
